id: strace-mmiyoo
name: Miyoo strace
modified_source: no
version: "6.12"
source:
  url: https://github.com/strace/strace/releases/download/v6.12/strace-6.12.tar.xz
  sha256: c47da93be45b6055f4dc741d7f20efaf50ca10160a5b100c109b294fd9c0bdfe
artifact:
  type: tool_bundle
  output_name: strace-mmiyoo
