#!/usr/bin/env bash
set -euo pipefail

package_id="${1:?missing package id}"
root="${2:?missing repository root}"
source_dir="${3:?missing source directory}"
host_root="${4:?missing host root}"

[[ "$package_id" == "konpacto-mmiyoo" ]] || exit 1

deps_dir="$host_root/deps"
mkdir -p "$deps_dir"

# konpacto's own Makefile targets a Windows/MinGW host build against prebuilt
# libraries in sibling directories that do not exist here. Replace it with a
# plain Linux recipe rather than trying to coax the upstream one into working.
luajit_prefix="$deps_dir/luajit"
luajit_source="$deps_dir/LuaJIT"

if pkg-config --exists luajit; then
  luajit_pkg_config_path=""
else
  if [[ ! -f "$luajit_source/Makefile" ]]; then
    rm -rf "$luajit_source"
    if [[ -n "${HOST_LUAJIT_SOURCE_DIR:-}" ]]; then
      git clone --shared "$HOST_LUAJIT_SOURCE_DIR" "$luajit_source" >/dev/null
    else
      git init "$luajit_source" >/dev/null
      git -C "$luajit_source" remote add origin https://github.com/LuaJIT/LuaJIT.git
      git -C "$luajit_source" fetch --depth 1 origin 1ee778a4e37122d8ca7d5733c590a47dafd6b15c >/dev/null
      git -C "$luajit_source" checkout --detach FETCH_HEAD >/dev/null
    fi
  fi

  if [[ ! -f "$luajit_prefix/lib/pkgconfig/luajit.pc" || ! -e "$luajit_prefix/lib/libluajit-5.1.so" ]]; then
    make -C "$luajit_source" clean >/dev/null 2>&1 || true
    make -C "$luajit_source" -j"${HOST_JOBS:-$(nproc)}" \
      CFLAGS="-fPIC" BUILDMODE=dynamic
    make -C "$luajit_source" install PREFIX="$luajit_prefix"
  fi
  luajit_pkg_config_path="$luajit_prefix/lib/pkgconfig"
fi

if [[ -n "$luajit_pkg_config_path" ]]; then
  export PKG_CONFIG_PATH="$luajit_pkg_config_path${PKG_CONFIG_PATH:+:$PKG_CONFIG_PATH}"
fi
pkg-config --exists luajit || {
  printf 'Native LuaJIT was not found after preparation.\n' >&2
  exit 1
}
printf '%s\n' "$luajit_pkg_config_path" > "$host_root/luajit-pkgconfig-path"

# The PKG_CONFIG_PATH export above only lives for this script's own process;
# build-host.sh invokes `make` as a separate process afterwards that never
# sees it. Resolve LuaJIT's flags now and bake them into the Makefile as
# literals instead of leaving `make` to re-run pkg-config for luajit itself.
luajit_cflags="$(pkg-config --cflags luajit)"
luajit_libs="$(pkg-config --libs luajit)"

# konpacto's source does not vendor tinydir.h; fetch the header it expects.
tinydir_dir="$deps_dir/tinydir"
if [[ ! -f "$tinydir_dir/tinydir.h" ]]; then
  rm -rf "$tinydir_dir"
  git init "$tinydir_dir" >/dev/null
  git -C "$tinydir_dir" remote add origin https://github.com/cxong/tinydir.git
  git -C "$tinydir_dir" fetch --depth 1 origin 1.2.6 >/dev/null
  git -C "$tinydir_dir" checkout --detach FETCH_HEAD >/dev/null
fi
install -m 644 "$tinydir_dir/tinydir.h" "$source_dir/src/tinydir.h"

cat > "$source_dir/Makefile" <<'EOF'
# Generated by packages/konpacto-mmiyoo/scripts/prepare-host.sh for the
# buildbot's Linux host lane. konpacto's own Makefile targets Windows/MinGW
# against prebuilt sibling-directory libraries that do not exist here.
CC ?= gcc
PKG_CONFIG ?= pkg-config

LUAJIT_CFLAGS := @@LUAJIT_CFLAGS@@
LUAJIT_LIBS := @@LUAJIT_LIBS@@

CFLAGS += -O0 -g -Wall -std=gnu11 -Isrc $(shell $(PKG_CONFIG) --cflags sdl2 SDL2_image SDL2_mixer) $(LUAJIT_CFLAGS)
LDLIBS := $(shell $(PKG_CONFIG) --libs sdl2 SDL2_image SDL2_mixer) $(LUAJIT_LIBS) -lm -ldl -lpthread

SOURCES := src/lua.c src/screen.c src/input.c src/pages.c src/file.c src/ui.c \
           src/main.c src/sound.c src/synth.c src/sequence.c

.PHONY: all
all: build/konpacto

build/konpacto: $(SOURCES)
	mkdir -p build
	$(CC) $(CFLAGS) $(SOURCES) $(LDLIBS) -o $@

.PHONY: clean
clean:
	rm -rf build
EOF

sed -i \
  -e "s|@@LUAJIT_CFLAGS@@|$luajit_cflags|" \
  -e "s|@@LUAJIT_LIBS@@|$luajit_libs|" \
  "$source_dir/Makefile"

printf 'konpacto host Makefile staged at %s/Makefile\n' "$source_dir"
