id: sdl2-benchmarks-mmiyoo
name: Miyoo SDL2 Benchmarks
modified_source: no
version: latest
source:
  repo: https://github.com/XK9274/miyoo_sdl2_benchmarks.git
  ref: main
depends_on:
  - sdl2-mmiyoo-lib
  - sdl2-mmiyoo-addons
build_all: false
app_dist:
  template: packages/sdl2-benchmarks-mmiyoo/templates
  output_name: sdl_bench
