id: blobbyvolley2-mmiyoo
name: Blobby Volley 2 for Miyoo Mini family
version: c28c5fa87872b7592f34f5f86196e93d127b6cf9
source:
  repo: https://github.com/danielknobe/blobbyvolley2.git
  ref: c28c5fa87872b7592f34f5f86196e93d127b6cf9
depends_on:
  - sdl2-mmiyoo-lib
build_all: false
app_dist:
  template: packages/blobbyvolley2-mmiyoo/templates
  output_name: BlobbyVolley2
host:
  build_system: cmake
  source_dir: .
  pkg_config:
    - sdl2
  prepare_script: packages/blobbyvolley2-mmiyoo/scripts/prepare-host.sh
  run_script: packages/blobbyvolley2-mmiyoo/scripts/run-host.sh
  configure_args:
    - -DBUILD_TESTS=OFF
  build_target: blobby
  outputs:
    - build/src/blobby
