id: blobbyvolley2-mmiyoo
name: Blobby Volley 2 for Miyoo Mini family
modified_source: yes
version: latest
source:
  repo: https://github.com/XK9274/blobbyvolley2.git
  ref: miyoo
depends_on:
  - sdl2-mmiyoo-lib
build_all: true
artifact:
  type: port
  output_name: blobbyvolley2-mmiyoo
host:
  build_system: cmake
  source_dir: .
  pkg_config:
    - sdl2
  prepare_script: packages/blobbyvolley2-mmiyoo/scripts/prepare-host.sh
  run_script: packages/blobbyvolley2-mmiyoo/scripts/run-host.sh
  configure_args:
    - -DBUILD_TESTS=OFF
  build_target: blobby
  outputs:
    - build/src/blobby
