id: sdl2-mmiyoo-addons
name: SDL2 image, TTF, net, and mixer add-ons for MMIYOO SDL2
modified_source: no
version: 7e998b923738d3b00e3a2867c8aa29c4b7b1d06a
source:
  repo: https://github.com/Yorisoft/pokedex_miyoo.git
  ref: 7e998b923738d3b00e3a2867c8aa29c4b7b1d06a
depends_on:
  - sdl2-mmiyoo-lib
build_all: false
artifact:
  type: tool_bundle
  output_name: sdl2-mmiyoo-addons
