id: love-mmiyoo-demo
name: LÖVE Miyoo SDL2/GLES Demo
version: 11.5
build_all: true
source:
  repo: https://github.com/love2d/love.git
  ref: f834ab72481e95fa90abf573643c8dd168ae0660
depends_on:
  - sdl2-mmiyoo-lib
app_dist:
  template: packages/love-mmiyoo-demo/templates
  output_name: LoveMiyoo
